### ISSUE TITLE
Unable to upgrade rasa-x via Server quick install script

### ISSUE THREAD

**Issue by hakob17** [RasaHQ/rasa-x-helm#104]
When running server quick install script for updating, i.e. `curl -s get-rasa-x.rasa.com | sudo bash` I get an error 

Error: UPGRADE FAILED: template: rasa-x/templates/rasa-x-service.yaml:8:16: executing "rasa-x/templates/rasa-x-service.yaml" at <.Values.rasax.service.annotations>: nil pointer evaluating interface {}.annotations

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tczekajlo** [comment]
Hi,

You can upgrade your helm chart version by executing the following commands:

1. `helm get values rasa-x -o yaml > values.yaml`
2. `helm upgrade rasa-x rasa-x/rasa-x -f values.yaml`

and then

3. `curl -s get-rasa-x.rasa.com | sudo bash`

https://github.com/RasaHQ/rasa-x-helm/issues/102

**Comment by hakob17** [comment]
> 1. `helm get values rasa -o yaml > values.yaml`
> 2. `helm upgrade rasa rasa-x/rasa-x -f values.yaml`
> 
> and then
> 
> 1. `curl -s get-rasa-x.rasa.com | sudo bash`

Hi this worked for me, thanks a lot
