### ISSUE TITLE
Feature: extraManifests support

### ISSUE THREAD

**Issue by shubhamc183** [RasaHQ/rasa-x-helm#110]
We can have a way to specify the `extraManifests` so that we can create extra resources like Secret which can be used by `existingSecret` from the chart only.

For example.
`extraManifests.[]` : https://github.com/airflow-helm/charts/tree/main/charts/airflow#docs-kubernetes---additional-manifests

Implementation: https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/extra-manifests.yaml
```
{{- range .Values.extraManifests }}
---
{{ tpl (toYaml .) $ }}
{{- end }}
```

Please let me know If I can send a PR?

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by degiz** [comment]
@tczekajlo Could you please take a look?

**Comment by tczekajlo** [comment]
@shubhamc183 Thanks for the issue. I see your point but I think that the rasa-x helm chart is not a perfect place to do this kind of additional operations. There're better ways to apply extra manifests before the chart installation, e.g. [helmfile ](https://github.com/roboll/helmfile#hooks) has the `hooks` feature that can be you to apply additional resources.
