### ISSUE TITLE
How to disable authentication in rasa-x

### ISSUE THREAD

**Issue by ahmedTouati** [RasaHQ/rasa-x-helm#111]
Hello, we want to integrate OAuth authentication using Nginx ingress to authenticate to rasa-x and so we need to disable the default login form in rasa-x. However, there is no available option in the rasa-x helm to do so.

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by amn41** [comment]
hi @ahmedTouati - thanks for the feature request! Unfortunately this isn't something we support. We do have SSO support and role-based access control but only as Rasa Enterprise features.
