### ISSUE TITLE
Show the Rasa CE generated password after the installation

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa-x-helm#13]
Currently, the following information is shown after the successful `rasa-x-helm` installation:
```
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thanks for installing Rasa X  !

Creating a Rasa X user:

- Rasa X CE: go to the terminal of the `rasa-x` pod and then
  execute `python scripts/manage_users.py create --update me <your password> admin`
  to set your password
- Rasa X EE: go to the terminal of the `rasa-x` pod and then
  execute `python scripts/manage_users.py create <your username> <your password> <role of your user>`.
  You can then log in using these credentials.

Also check out the Rasa X docs here for more help:
https://rasa.com/docs/rasa-x/
```

We show that the password can be changed but this information is not sufficient (it doesn't include any information about what specific pod you should access and how to do that), so the idea is to show the generated password after the successful installation.

**Comment by m-vdb** [comment]
@alwx isn't this already done in [here](https://github.com/RasaHQ/rasa-x/blob/cdb959b3ee771b18a0761bef08ed2c8e486c29a6/deployment/cluster-deployment-script/get-rasa-x.sh#L353)?

**Comment by alwx** [comment]
Yes, it's done.
