### ISSUE TITLE
Deployment of production and worker fails due to latest alpine image

### ISSUE THREAD

**Issue by loomsen** [RasaHQ/rasa-x-helm#130]
# short description
Hi,

our deployments start failing due to the latest update of the alpine image, which is used for the init-db container.

Production and worker pods remain in Init, because the init-db container doesn't finish.

# long story

The change must have been introduced between `alpine@sha256:3c7497bf0c7af93428242d6176e8f7905f2201d8fc5861f45be7a346b5f23436` and `alpine:latest` which at the time of this writing is `alpine@sha256:d9a7354e3845ea8466bb00b22224d9116b183e594527fb5b6c3d30bc01a20378`.

The problem is, that nslookup now returns 1 instead of 0 for `nslookup rasa-x-db-migration-service-headless`.

```
 nvarz:~$ k8s_run_image alpine@sha256:3c7497bf0c7af93428242d6176e8f7905f2201d8fc5861f45be7a346b5f23436 
/ # nslookup rasa-x-db-migration-service-headless 1>/dev/null; echo $?
0


 nvarz:~$ k8s_run_image alpine:latest
/ # nslookup rasa-x-db-migration-service-headless 1>/dev/null; echo $?
1
```

This in turn causes the until loop to run forever:
```
until nslookup rasa-x-db-migration-service-headless 1> /dev/null; do echo Waiting for the database migration service; sleep 2; done 
```

and thus the init-db doesn't return success and the production and worker pods are stuck in Init:
```
rasa-x-app-749447984-sxkc6                1/1     Running    0          48m
rasa-x-db-migration-service-0             1/1     Running    2          48m
rasa-x-duckling-85b858bc77-6kvl4          1/1     Running    0          48m
rasa-x-postgresql-0                       1/1     Running    0          48m
rasa-x-rabbit-0                           1/1     Running    0          48m
rasa-x-rasa-production-7c894fb75b-fzdgq   0/1     Init:0/1   0          48m
rasa-x-rasa-worker-759584656-9mml9        0/1     Init:0/1   0          48m
rasa-x-rasa-x-757fd968fc-brmml            1/1     Running    0          48m
rasa-x-redis-master-0                     1/1     Running    0          48m
```

# current workaround

To workaround this problem we can use:
```
--set dbMigrationService.initContainer.image="alpine@sha256:3c7497bf0c7af93428242d6176e8f7905f2201d8fc5861f45be7a346b5f23436"
```
in our helm command.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by kaustuk** [comment]
@loomsen  Even we are facing this issue. Thanks giving workaround. Will use it until this is fixed

**Comment by kaustuk** [comment]
> Thanks for raising this issue, @rctatman will get back to you about it soon✨
> 
> ###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

@rctatman The fix I was think was would be adding `not` condition [here](https://github.com/RasaHQ/rasa-x-helm/blob/f35216d3c24e540143f71c6b2f973282936fc72c/charts/rasa-x/templates/_helpers.tpl#L275). Here assuming that going forward `alpine` would give zero for `nslookup rasa-x-db-migration-service-headless`.

@rctatman do you think that would fix the issue? Should I open a PR for this or are there other considerations?

**Comment by kaustuk** [comment]
@loomsen Can you try updating you chart version to latest i.e `1.7.14`? It works for me. Earlier I was facing issue in chart version `1.7.13`. 

From comparing diff between 1.7.14 to 1.7.13 you will see that in 1.7.13 was using `alpine:latest` and in `1.7.14` now uses `alpine:3.12.3`. I guess that latest version of alpine have changed definition of nslookup so we might have faced that issue

**Comment by rgstephens** [comment]
`1.17.14` chart with latest alpine does address this issue.

**Comment by loomsen** [comment]
Sorry, got dragged into another topic, yeah, it works. Thank you.
