### ISSUE TITLE
Problem starting rasa-x default chart in digital ocean kubernetes

### ISSUE THREAD

**Issue by AdamFerguson** [RasaHQ/rasa-x-helm#14]
Hi, I've been trying to spin up this helm chart in a digital ocean kubernetes cluster for the last few days but have been unsuccessful. I finally tracked the issue down to a couple things and thought I should share them:

1) For whatever reason, the default app version, which is based off the `.Chart.AppVersion` of 0.24.1 is failing. When I specifically set the tags for `rasax`, `eventService`, and `nginx` to 0.24.7, those issues resolved themselves.

2) The PVC claim that rasa-x was making. It seems that, by default, it tries to claim a storage class of "standard" whereas DO clusters seem to want a storage class of "do-block-storage". 

The other three PVC's that are created through this chart, from the helm stable charts, all are created successfully. I think it's b/c by default those charts use templates that inspect the global state. For instance, below is the template from the postgres helm chart.

I'd like to propose using a similar template for the rasa-x storage class.

```
{{/*
Return  the proper Storage Class
*/}}
{{- define "postgresql.storageClass" -}}
{{/*
Helm 2.11 supports the assignment of a value to a variable defined in a different scope,
but Helm 2.9 and 2.10 does not support it, so we need to implement this if-else logic.
*/}}
{{- if .Values.global -}}
    {{- if .Values.global.storageClass -}}
        {{- if (eq "-" .Values.global.storageClass) -}}
            {{- printf "storageClassName: \"\"" -}}
        {{- else }}
            {{- printf "storageClassName: %s" .Values.global.storageClass -}}
        {{- end -}}
    {{- else -}}
        {{- if .Values.persistence.storageClass -}}
              {{- if (eq "-" .Values.persistence.storageClass) -}}
                  {{- printf "storageClassName: \"\"" -}}
              {{- else }}
                  {{- printf "storageClassName: %s" .Values.persistence.storageClass -}}
              {{- end -}}
        {{- end -}}
    {{- end -}}
{{- else -}}
    {{- if .Values.persistence.storageClass -}}
        {{- if (eq "-" .Values.persistence.storageClass) -}}
            {{- printf "storageClassName: \"\"" -}}
        {{- else }}
            {{- printf "storageClassName: %s" .Values.persistence.storageClass -}}
        {{- end -}}
    {{- end -}}
{{- end -}}
{{- end -}}
```

**Comment by wochinge** [comment]
Hi @AdamFerguson ,

thanks for creating the issue! 
I think what they do differently, is that they don't specify an initial Storageclass but leave it empty by default (https://github.com/helm/charts/blob/2053ca44331b54888f4189cd210994ac1c8dda9e/stable/postgresql/values.yaml#L10). I remember we had problems with leaving it empty when upgrading. We will re-check it 👍

**Comment by wochinge** [comment]
Seems they fixed this in https://github.com/helm/helm/issues/6642 👍

**Comment by wochinge** [comment]
@AdamFerguson Fixed and released 🎉

**Comment by AdamFerguson** [comment]
@wochinge Thank you!
