### ISSUE TITLE
service type is not configurable for rasa and rasa-x services [default type is ClusterIP]

### ISSUE THREAD

**Issue by nakshathru** [RasaHQ/rasa-x-helm#143]
I'm trying to use ingress instead of nginx reverse proxy, since my requirement involves multiple rasa namespaces and use of aws-load-balancer-controller.

But aws-load-balancer-controller failed to setup because default service type is ClusterIP and it has to be NodePort type.
I'm able to change it to NodePort for rabbitmq service using the existing values.yml file
But the configurable service type is not present for rasa, rasa-x service.

Attaching aws-load-balancer-controller issue reference:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1695

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by degiz** [comment]
cc @tczekajlo

**Comment by rgstephens** [comment]
@tczekajlo I think we should move `port` to `service.port` along with allowing specification of service `type`, `nodePort` and `loadBalancerIP`.  WDYT?

I'm putting together a PR that supports `port` & `service.port` with priority given to `service.port`.

**Comment by tczekajlo** [comment]
> @tczekajlo I think we should move `port` to `service.port` along with allowing specification of service `type`, `nodePort` and `loadBalancerIP`. WDYT?
> 
> I'm putting together a PR that supports `port` & `service.port` with priority given to `service.port`.
> 
> ```yaml
> rasax:
>   service:
>     type: ClusterIP
>     port: 5002
>     nodePort: 
>     loadBalancerIP:
> 
> versions:
>   rasaProduction:
>     type: ClusterIP
>     port: 5005
>     nodePort:
>     loadBalancerIP:
> ```

Hmm, exposing directly rasa and rasa-x services won't work. We add additional configuration to the nginx/or ingress-nginx that is required by the services and exposing them without this configuration will make that at some point they don't work correctly.

If we wanna add the only support for a service type that's ok, but if users will want to use it to expose services directly it won't work without additional configuration on their side.

**Comment by rgstephens** [comment]
@tczekajlo can you be more specific?  I made changes to the `rasa-config-files-configmap.yaml` and `rasa-deployment.yaml` and currently have a working install on this branch.

**Comment by tczekajlo** [comment]
> @tczekajlo, thanks for pointing that out. I made changes to the `rasa-config-files-configmap.yaml` and `rasa-deployment.yaml` and currently have a working install on this branch.
> 
> I'll review the `rasax.nginx` config.
> 
> Can you give me an idea of what configuration items you're thinking of? Is there something about my current PR that would cause an issue?
> 
> ```
> /
> /robots.txt
> /core/
> /webhooks/
> /socket.io
> /api/ws
> /api/chat
> /nginx_status
> ```

I think that the ingress-nginx configuration shows well what has to be added to an ingress/proxy/whatever is used to get it to work.

https://github.com/RasaHQ/rasa-x-helm/blob/main/charts/rasa-x/templates/rasa-x-ingress.yaml
https://github.com/RasaHQ/rasa-x-helm/blob/main/charts/rasa-x/templates/rasa-open-source-ingress.yaml

For rasa-x we have to add rewrite for paths and add headers:

```
      if ($arg_environment = "") {
          rewrite ^/api/chat$ /core/webhooks/rasa/webhook last;
      }
      if ($arg_environment = "production") {
          rewrite ^/api/chat$ /core/webhooks/rasa/webhook last;
      }
      if ($request_uri ~ ^/robots.txt$) {
          return 200 "User-agent: *\nDisallow: /\n";
      }
```

and

```
add_header X-Robots-Tag none;
```

Fox rasa, we have to remember to redirect all requests for the following paths to the rasa backend:

```
/core/(.*)
/webhooks/
/socket.io
```

and the last thing, we have to remember to update connections for `/api/ws` (ingress-nginx is doing it automatically so we don't add it to ingress configuration, but we have it in the nginx image)

**Recap**
Your current PR looks good in general, and I think with some small changes we can merge it soon. The issue I see here is a bit different, probably if someone exposes the rasa and rasa-x services directly then expect that it's going to work, so I think we should document/say clearly that "you can do that BUT be aware  it requires additional configuration on your side"

**Comment by tczekajlo** [comment]
@rgstephens next week I'm off, if you need any input please ping @RasaHQ/infrastructure

**Comment by rgstephens** [comment]
After looking through the endpoints, it seems like the main one that needs to be available if someone isn't using the nginx image or ingress is `/app/ws` which is used by `rasa-production` and `rasa-worker`.

To finish up the PR I'll add notes in the README about the additional configuration requirement.

**Comment by rgstephens** [comment]
@tczekajlo I think this is ready and that there is no additional config requirement that needs to be documented.

**Comment by tczekajlo** [comment]
Support for setting service type for Rasa X was added in the 4.2 version. The rasa production deployment is deprecated and not supported anymore, please use the dedicated chart for it (https://helm.rasa.com).
