### ISSUE TITLE
Add an OpenShift Helm Chart Repo CRD

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-x-helm#145]
Add the Helm Chart Repo CR for Rasa-X as described in OpenShift [docs](https://docs.openshift.com/container-platform/4.6/cli_reference/helm_cli/configuring-custom-helm-chart-repositories.html)

**Comment by tmbo** [comment]
@akelad do you know if any customer is currently needing this? otherwise I'd move it to future

**Comment by tmbo** [comment]
will move to future.

**Comment by andreoid** [comment]
Issue moved to JIRA: INFRA-32
