### ISSUE TITLE
running "VolumeBinding" filter plugin for pod "rasa-x-1617074480-postgresql-0": pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by collinarnett** [RasaHQ/rasa-x-helm#170]
Hello,

I'm trying to setup rasa x on a local minikube deployment and I'm using Lens to inspect the start up.
I'm getting the error:
```
running "VolumeBinding" filter plugin for pod "rasa-x-1617074480-postgresql-0": pod has unbound immediate PersistentVolumeClaims
```

when installing the helm chart. I'm pretty new to Kubernetes and Helm so I'm unsure of how to diagnose this.

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by rgstephens** [comment]
This looks like it prometheus related based on what I see [here](https://github.com/prometheus/alertmanager/issues/2362). Are all of the pods running and can you connect to Rasa X?

**Comment by RASADSA** [comment]
this is an error related your local minikube PVC setup which doesnt seem to be working - not related to the rasa x helm chart
