### ISSUE TITLE
Default nginx liveness and readiness probes broken

### ISSUE THREAD

**Issue by maxbischoff** [RasaHQ/rasa-x-helm#173]
In 4d1a1f19a19d5c20a30126deffe669a1c71ae9e8 the chart renders invalid kubernetes manifests when using default nginx probes (i.e. when `nginx.livenessProbe.command` or `nginx.readinessProbe.command` is unset).

Our installation pipeline for the chart failed with error `Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe): unknown field "exec:command" in io.k8s.api.core.v1.Probe, ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe): unknown field "exec:command" in io.k8s.api.core.v1.Probe]`.

I provided a fix with sample outputs for the current and my fixed version in https://github.com/RasaHQ/rasa-x-helm/pull/172

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Haha, good job sara-tagger -- closed in #172, thank you for the PR!
