### ISSUE TITLE
my-release app issue with no pod, deployment and service running

### ISSUE THREAD

**Issue by stevelam20** [RasaHQ/rasa-x-helm#175]
my-release app pod, deployment and service are not responding 

![event error for my-release app](https://user-images.githubusercontent.com/460801/114744730-966c8080-9d80-11eb-8797-ee56ec154010.JPG)
![service has no endpoint addresses](https://user-images.githubusercontent.com/460801/114744751-9b313480-9d80-11eb-8e90-07bb4b8d13d7.JPG)
![my-release-app pod is empty](https://user-images.githubusercontent.com/460801/114744776-9f5d5200-9d80-11eb-932d-099cc215e294.JPG)
![expected replicas, but 0 is available](https://user-images.githubusercontent.com/460801/114744800-a5ebc980-9d80-11eb-844a-4fd5a95afd73.JPG)
![deployment for my-release app no replicas exist for this deployment](https://user-images.githubusercontent.com/460801/114744824-aedc9b00-9d80-11eb-9841-30875e577494.JPG)

**Comment by erohmensing** [comment]
fixed in https://github.com/RasaHQ/rasa-x-helm/pull/176, thanks for the contribution
