### ISSUE TITLE
Configurable Model Storage Location For Rasa X Helm Chart Deployment

### ISSUE THREAD

**Issue by nakshathru** [RasaHQ/rasa-x-helm#178]
Rasa provides the flexibility of using AWS S3 or any other cloud service as model storage by updating endpoint.yml file.
But it is not available while deploying via Rasa X helm chart in EKS.

`        name: "RASA_MODEL_SERVER"`
`            value: {{ $.Values.rasax.scheme }}://{{ include "rasa-x.host" $ }}.{{ $.Release.Namespace }}.svc:{{ $.Values.rasax.port }}/api/projects/default/models/tags/{{ .modelTag }}`

This is the current model server url found in the deployment template, which only takes the default pod location as model storage location. But not configurable via values.yml file.
Our use case involves using S3 as model storage with periodic pulling of latest models while keeping the Rasa X setup in EKS cluster.

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by HotThoughts** [comment]
`v2.0` of rasa-x-helm chart supports external Rasa OSS deployment. If you use a dedicated chart for Rasa instead of being part of Rasa X, you can [config the endpoint](https://github.com/RasaHQ/helm-charts/blob/9be1bf6d9ef72436c354b533489d4c53a4209a96/charts/rasa/values.yaml#L68) for model server.
