### ISSUE TITLE
How to use different image for rasa worker and rasa production?

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasa-x-helm#184]
Is there a way to set `values.yml` so that a different image is used for the rasa production and rasa worker deployment?

The use case is that I want to train my bot on a GPU and the current solution for this is to use a [custom dockerfile](https://github.com/RasaHQ/rasa/issues/7950).

**Comment by tczekajlo** [comment]
👋🏻 Currently, there is no option to define a diffrent image for rasa production and rasa worker.
