### ISSUE TITLE
upgrade RabbitMQ chart version

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa-x-helm#197]
Upgrading to RabbitMQ subchart version >7.0.0 introduces breaking changes, but also useful options.
https://artifacthub.io/packages/helm/bitnami/rabbitmq/7.8.0#to-7-0-0
An upgrade would require warning users when updating the helm chart since it could disrupt their existing deployment

**Comment by virtualroot** [comment]
In https://github.com/RasaHQ/helm-charts we are aiming for RabbitMQ subchart v8.12.2.
Migrating to the new helm chart is going to be disrupting by itself + RabbitMQ upgrade.

@melindaloubser1 Do you think is worth keeping this issue open? Or do we better leave it for the next Helm chart gen? 🚀

**Comment by melindaloubser1** [comment]
I think close it and leave it for next gen👍
