### ISSUE TITLE
Unable to start using k3s

### ISSUE THREAD

**Issue by csd-oss** [RasaHQ/rasa-x-helm#226]
I am trying to install Rasa X and Rasa using https://rasa.com/docs/rasa-x/installation-and-setup/install/quick-install-script#embedded-cluster-installation

I have Ubuntu 20.04 server with 2vCPU and 4GB Ram.
Loged in as root. 

After I do:

> curl -s get-rasa-x.rasa.com | sudo bash

I get infinite 

> Deploying Rasa X ... 

loading screen. 
And postgres, redis and rabbit can't start
![image](https://user-images.githubusercontent.com/58642039/130366097-d1b99a99-9f13-45af-9bc7-372ed851fb29.png)

My postgres log's

> postgresql 18:28:32.75 INFO  ==> Initializing PostgreSQL database...
> mkdir: cannot create directory ‘/bitnami/postgresql’: Permission denied
> postgresql 18:28:32.77 INFO  ==> Stopping PostgreSQL...

My redis log's

>  18:31:10.57 INFO  ==> ** Starting Redis **
>1:C 22 Aug 2021 18:31:10.578 # Can't chdir to '/data': Permission denied

My rabbit log's

> touch: cannot touch '/opt/bitnami/rabbitmq/var/lib/rabbitmq/.start': Permission denied

I understand that all this three services having the same problem, but I haven't found easy fix and it seem's strange to fix something after one line installation script.

**Comment by sara-tagger** [comment]
Thanks for the issue, @desmarchris will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by desmarchris** [comment]
looks like a k3s issue with a latest release: https://github.com/k3s-io/k3s/issues/3704

they just shipped an update. So you can try with the updated version, or downgrade to an older k3s version

**Comment by RASADSA** [comment]
problem is related to bitnami postgers helmchart - will take a look

**Comment by csd-oss** [comment]
Yes, thanks. Uninstalling rasa, installing latest version of k3s and installing rasa again helped.
