### ISSUE TITLE
Only start a worker pod when required to conserve resources

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa-x-helm#237]
rasa-worker is one of the more resource-intensive pods in a rasa-x deployment, but it doesn't do anything most of the time. It is only required when a request is sent to train a model, or to run cross-validation.

The suggestion is to make training/cross-validation requests trigger the starting of a rasa-worker pod, potentially as a job, not a deployment, and have the pod/job stop when training or cross-validation is completed. 

@virtualroot mentioned this would require creating a service account with enough privileges for Rasa X to be able to spin up new pods or run a job.

**Comment by plattenschieber** [comment]
Why did you close this issue @virtualroot? This is still an issue on our and potentially many more Rasa X users site. 

Either unnecessary resources are blocked or human intervention is required to spin the worker up and down to not waste GPU resources. Is there any effort planned?

**Comment by virtualroot** [comment]
Hello @plattenschieber 

I closed this issue because this isn't the right place for tracking such product requests.

There is no planned work for it, but we understand the need and it's on our radar.
