### ISSUE TITLE
Redis password not provided when external redis used

### ISSUE THREAD

**Issue by nyejon** [RasaHQ/rasa-x-helm#247]
@RASADSA should I open a separate issue for the Redis install issue then?

That was also not addressed as pointed out by @pierluigilenoci in https://github.com/RasaHQ/rasa-x-helm/issues/211#issuecomment-880736816

_Originally posted by @nyejon in https://github.com/RasaHQ/rasa-x-helm/issues/211#issuecomment-934297146_

**Comment by nyejon** [comment]
Figured this must have gotten lost in the comments

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by pierluigilenoci** [comment]
@RASADSA @erohmensing any news about this?

**Comment by pierluigilenoci** [comment]
@RASADSA @erohmensing any news about this?

**Comment by pierluigilenoci** [comment]
Maybe @virtualroot?
