### ISSUE TITLE
Add support to the new IngressClassName spec

### ISSUE THREAD

**Issue by pierluigilenoci** [RasaHQ/rasa-x-helm#263]
Since K8s 1.18 the annotation `kubernetes.io/ingress.class` is deprecated.
It would be very useful to have support for the new `IngressClassName` spec inside the chart. 

Ref: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#deprecating-the-ingress-class-annotation

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @pythenry will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by pierluigilenoci** [comment]
@virtualroot I got to check out the update just today.

Thanks for the work but there is still a small step away. The ingress for RasaX is left out. 
Ref: https://github.com/RasaHQ/rasa-x-helm/blob/main/charts/rasa-x/templates/rasa-x-ingress.yaml

I created a new ticket for that #270
