### ISSUE TITLE
[FR] Allow the Chart to create extra manifest

### ISSUE THREAD

**Issue by pierluigilenoci** [RasaHQ/rasa-x-helm#269]
Sometimes, accessory to the installation there may be manifest to be installed (for example a SecretProviderClass, NetworkPolicies, PVC).

It would be nice to be able to do this directly via the Chart using the approach that ArgoCD also uses.

Ref: https://github.com/argoproj/argo-helm/blob/cf57a71a154a1a8a19f5f9d3980d60eb3efd80c8/charts/argo-cd/values.yaml#L62-L87

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @joejuzl will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by pierluigilenoci** [comment]
@joejuzl @virtualroot any news?

**Comment by virtualroot** [comment]
@pierluigilenoci Thanks for bringing this idea to us.

We have decided against implementing this feature in the Helm chart.
For applying additional manifest, our suggestion is to use `helmfile` [hooks](https://github.com/roboll/helmfile#hooks) instead.

**Comment by pierluigilenoci** [comment]
@virtualroot I accept your refusal although I would prefer to have a technically detailed answer on the reasons for the refusal.

The use of a third party tool such as helmfile is out of the question as it is not supported by the GitOps tool we use (FluxCD, tool incubated by the CNCF) and is an unnecessary complication.

The requested feature did not involve any complications and would have been very useful. So much so that it is used in some of the most famous charts such as that of Grafana or those produced by Bitnami. Even the ArgoCD chart (the other GitOps tool) implements it. 

I am sorry but given how other issues/FR were handled by the Rasa team and the quality of Rasa X chart I am not disappointed or amazed.
