### ISSUE TITLE
[FR] Upgrade the chart to use Rasa v3.*

### ISSUE THREAD

**Issue by pierluigilenoci** [RasaHQ/rasa-x-helm#271]
It would be great if you updated the chart to be able to use Rasa v3. ❤️

**Comment by tczekajlo** [comment]
Rasa X is not compatible with Rasa OSS 3.x - https://rasa.com/docs/rasa-x/changelog/compatibility-matrix/

**Comment by pierluigilenoci** [comment]
@tczekajlo and then make it compatible. 🚀
