### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-x-helm#38]
Documentation question

- Should `Chart.appVersion` in the table be `rasax.tag`
- How to add the `--debug` option to the rasa startup args
- How do I add channel code to rasa-production

**Comment by wochinge** [comment]
@rgstephens 

> Should Chart.appVersion in the table be rasax.tag

True, should removed / replaced with `rasax.tag` 👍 
> How to add the --debug option to the rasa startup args

Makes sense to also cover in the README even though it's also covered in the docs 👍 

> How do I add channel code to rasa-production

This is documented in the linked Rasa X documentation. I think I wouldn't duplicate it here.

**Comment by andreoid** [comment]
> Should Chart.appVersion in the table be rasax.tag

This was fixed 12+ months back.

We've decided not to implement the other suggestions, due to duplication.
