### ISSUE TITLE
extraEnvs for eventService

### ISSUE THREAD

**Issue by ArjaanBuijk** [RasaHQ/rasa-x-helm#43]
This will allow use of custom schemas with a postgres database.

See [rasa x changelog](https://rasa.com/docs/rasa-x/rasa-x-changelog/#improvements) for description of the `POSTGRESQL_SCHEMA` environment variable, which needs to be set on the `rasax`, `rasa` and `eventService` services. 

Also update rasa x documentation page on kubernetes-openshift.

**Comment by wochinge** [comment]
done https://github.com/RasaHQ/rasa-x-helm/blob/c17b2bbac77a0580b4b217f6ba20e6eb94bd9b76/charts/rasa-x/values.yaml#L177
