### ISSUE TITLE
PV not created.

### ISSUE THREAD

**Issue by RielKIM** [RasaHQ/rasa-x-helm#44]
Hi, I have some problem using helm.

When I tested to deploy rasa using kubernetes and helm, I have faced a problem that it wouldn't be created PV.
It tried on minikube.
So, I tested again on google kubernetes service as a tutorial.
It was working well and PV was generated automatically.
So I tried to find a helm script about declaring of PV but, I can't find that.
So, What's problem of this issue?

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
Hi @RielKIM ,

which version of the Helm chart did you use? And could please share some error logs?

**Comment by RielKIM** [comment]
Hi,
I solved this issue.
I've create PV manually and restart all pods.
I just spend little bit time for making pv yaml file.
But now it's working well.
Thanks.

**Comment by wochinge** [comment]
@RielKIM Could you please share your created persistent volume yaml file? Would be great to fix this and share it with everyone.

**Comment by RielKIM** [comment]
Yes, I can share it.
As you know, google kuber. service, minikube and local kubeadm are not exactly same.
The file what I shared is used on kuber. cluster creating by local kubeadm.

[pv.yaml.txt](https://github.com/RasaHQ/rasa-x-helm/files/4507672/pv.yaml.txt)

The PV file has some problem.
First one is the name in claimRef which typed hard coded.
Second one is using hostPath. So I have plan to change storage type to nfs from hostpath.
Thanks.

**Comment by wochinge** [comment]
@RielKIM Thanks for sharing it. I just read the section `Dynamic provisioning and CSI
` in https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/  (+some parts of https://platform9.com/blog/tutorial-dynamic-provisioning-of-persistent-storage-in-kubernetes-with-minikube/ ) .

After reading that, I don't see why things shouldn't work out of the box. What was the exact error when running it without your persistent volume definition? What was the output of `kubectl get pvc` ? Which Rasa X Helm chart version are you using and which minikube version?
