### ISSUE TITLE
UPGRADE FAILED: "0.28.3" has no deployed releases

### ISSUE THREAD

**Issue by DROMZEE** [RasaHQ/rasa-x-helm#51]
The update is requested in the RASA-X interface
![rasa-upgrade](https://user-images.githubusercontent.com/12269933/81800599-5919c600-9513-11ea-98e7-1d74aa818c1e.png)

but the following commands

> helm repo update
> helm dependency update
> helm upgrade 0.28.3 rasa-x/rasa-x

returns this erros
> Error: UPGRADE FAILED: "0.28.3" has no deployed releases

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @chkoss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Hi @DROMZEE , I think this documentation is a bit out of date, can you please try upgrading with these instructions? https://rasa.com/docs/rasa-x/installation-and-setup/openshift-kubernetes/#upgrading-the-deployment

**Comment by DROMZEE** [comment]
Hi @erohmensing , Thank you very much and my apologies, it was well written in the documentation.
First update the values.yml files with 

> rasax:
>     tag: "0.28.3"

followed by commands
```
helm repo update
helm upgrade \
    --values values.yml \
    --namespace <your namespace> \
    --reuse-values \
    <your release name> rasa-x/rasa-x
```

**Comment by erohmensing** [comment]
No worries, it's not your fault, the `Update Rasa X` page linked from Rasa X had the wrong information, we'll update that page :)
