### ISSUE TITLE
Support multiple environments for Rasa Enterprise

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa-x-helm#53]
Rasa Enterprise supports [multiple deployment environments.](https://rasa.com/docs/rasa-x/enterprise/deployment-environments/).

The Helm chart currently doesn't support it since it is currently hardcoded to `production` and `worker`: https://github.com/RasaHQ/rasa-x-helm/blob/master/charts/rasa-x/templates/rasa-x-config-files-configmap.yaml.

The multiple rasa deployments / services are already created in a loop when added [here](https://github.com/RasaHQ/rasa-x-helm/blob/2902a50b3bf453dd350a7b3255f6ebc3e801df0e/charts/rasa-x/values.yaml#L120) . The missing piece hence is to 
- [ ] add the missing environments to the config map for `environments.yml`
- [ ] somewhat solve the problem that the version currently are named `rasaProduction` & `rasaWorker` in `values.yml`, but simple `production` and `worker` in the config map for `environments.yml`
- [ ] Document the procedure in the [kubernetes/openshift advanced configuration section](https://rasa.com/docs/rasa-x/installation-and-setup/openshift-kubernetes/#advanced-configuration)
- [ ] while at it, also update this out-of-date [documentation page on Deployment Environments](https://rasa.com/docs/rasa-x/enterprise/deployment-environments/). That page describes docker-compose, but will be linked to from the kubernetes/openshift page.

**Comment by wochinge** [comment]
@ArjaanBuijk how is this going?

**Comment by TyDunn** [comment]
@ArjaanBuijk What is the status of this?
