### ISSUE TITLE
Rasa X not reachable when using custom port

### ISSUE THREAD

**Issue by Smirl** [RasaHQ/rasa-x-helm#61]
# Summary

- When setting `.Values.rasax.port` it will change the rasax service port, but will not change the port rasax is using
- When adding `extraEnvs` to set `SELF_PORT` correctly, the service is hardcoded to point to 5002.
- Should be a simple PR to add `SELF_PORT` always, and update the target port to named like in other services

I will raise a PR

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
