### ISSUE TITLE
Ingress/Egress Requirements

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-x-helm#63]
Can we document the default ingress/egress requirements in the readme and the chart.  I think this are the defaults (not sure about the `event` service:

All connections are TCP unless indicated otherwise.

| Source            | Destination          |
| ----------------- | -------------------- |
| rasa-production   | rasa-x:5002          |
| rasa-production   | postgresql:5432      |
| rasa-production   | rabbit:5672          |
| rasa-production   | app:5055             |
| rasa-production   | duckling:8000        |
| rasa-production   | redis:6379           |
| rasa-x            | postgresql:5432      |
| rasa-x            | rasa-production:5005 |
| rasa-x            | rasa-worker:5005     |
| rasa-x            | event:5673           |
| rasa-x            | rabbit:5672          |
| event             | rabbit:5672          |
| app               | <tbd>             |
| nginx             | rasa-production:5005 |
| nginx             | rasa-x:5002          |
| \<Rasa X Users\>  | nginx:80             |
| \<Rasa Channels\> | nginx:80             |

**Comment by tczekajlo** [comment]
@rgstephens the default ingress is a simple, `kubectl get svc/ingress` should help. If I understand correctly the table describes egress, doesn't it? 

It looks good to me :)

**Comment by rgstephens** [comment]
Thanks

```
$ kubectl get svc
NAME                          TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                                 AGE
rasa-postgresql-headless      ClusterIP      None            <none>         5432/TCP                                13m
rasa-redis-headless           ClusterIP      None            <none>         6379/TCP                                13m
rasa-rabbit-headless          ClusterIP      None            <none>         4369/TCP,5672/TCP,25672/TCP,15672/TCP   13m
rasa-rasa-x-rasa-x            ClusterIP      10.43.195.93    <none>         5002/TCP                                13m
rasa-rasa-x-rasa-worker       ClusterIP      10.43.222.107   <none>         5005/TCP                                13m
rasa-rasa-x-rasa-production   ClusterIP      10.43.142.217   <none>         5005/TCP                                13m
rasa-rasa-x-duckling          ClusterIP      10.43.9.162     <none>         8000/TCP                                13m
rasa-rasa-x-app               ClusterIP      10.43.35.13     <none>         5055/TCP,80/TCP                         13m
rasa-redis-master             ClusterIP      10.43.83.167    <none>         6379/TCP                                13m
rasa-rabbit                   ClusterIP      10.43.200.102   <none>         4369/TCP,5672/TCP,25672/TCP,15672/TCP   13m
rasa-postgresql               ClusterIP      10.43.34.241    <none>         5432/TCP                                13m
rasa-rasa-x-nginx             LoadBalancer   10.43.248.236   192.168.64.2   8000:32700/TCP                          13m

$ kubectl get ingress
NAME          CLASS    HOSTS                ADDRESS        PORTS   AGE
rasa-rasa-x   <none>   rasa-x.example.com   192.168.64.2   80      16m
```

**Comment by rgstephens** [comment]
This is an update to the above adding `rasa-worker`:

| Source            | Destination          |
| ----------------- | -------------------- |
| rasa-production   | rasa-x:5002          |
| rasa-production   | postgresql:5432      |
| rasa-production   | rabbit:5672          |
| rasa-production   | app:5055             |
| rasa-production   | duckling:8000        |
| rasa-production   | redis:6379           |
| rasa-worker   | rasa-x:5002          |
| rasa-worker   | rabbit:5672          |
| rasa-x            | postgresql:5432      |
| rasa-x            | rasa-production:5005 |
| rasa-x            | rasa-worker:5005     |
| rasa-x            | event:5673           |
| rasa-x            | rabbit:5672          |
| event             | rabbit:5672          |
| app               | <tbd>             |
| nginx             | rasa-production:5005 |
| nginx             | rasa-x:5002          |
| \<Rasa X Users\>  | nginx:80             |
| \<Rasa Channels\> | nginx:80             |
