### ISSUE TITLE
Rasa X logs show rabbit PLAIN login refused: user ‘user’ - invalid credentials

### ISSUE THREAD

**Issue by soloman817** [RasaHQ/rasa-x-helm#64]
I got exactly the same issue as this post: https://forum.rasa.com/t/rasa-x-logs-show-rabbit-plain-login-refused-user-user-invalid-credentials/27609

I followed the documentation, added a values yaml file, and replaced my credentials.

Any idea?

**Comment by soloman817** [comment]
hmm, looks like if I change the password with only letters, and remove the image tag, now it works. My previous password contains alphabet and numbers and a "#" character.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
@soloman817 Thanks for creating an issue for this. I'm glad you were able to get it to work. I'll make sure the team looks into it, so future users do not struggle with it as well

**Comment by soloman817** [comment]
@TyDunn great. So I follow the docs, I copied a yaml content from the docs which is used to specify the credentials. and I changed ALL `<credentials>` to a password, which contains `#` character, such as `abc#123`. Then it won't work, and the rabbitmq log keeps saying the user "user" is invalid. Later I changed the credentials to only alphabet such as "abcdefg", then this work, hope this can help you.

**Comment by wochinge** [comment]
Not sure we can do much about this cc @tczekajlo

**Comment by soloman817** [comment]
@wochinge I think it's better to confirm that the password should not contain some special character, then update the document, that is good enough.

**Comment by tczekajlo** [comment]
@wochinge let's use a JSON schema to be sure that value for the `rabbitmq.password` parameter is correct.

**Comment by anatanick** [comment]
@soloman817 hello,I meet the same error as you did,and I have changed the password only with letters,but the error still exists.You have mentioned remove   image tag,you mean you remove what image,and in what file?
