### ISSUE TITLE
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'.

### ISSUE THREAD

**Issue by tczekajlo** [RasaHQ/rasa-x-helm#77]
For Rasa Open Source 2.0 in the logs, we can see the following error:

```
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-zj2d5evg because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing
```

It looks like we should add proper permissions for writing temporary files. @federicotdn @wochinge Have you seen this error before?

**Comment by federicotdn** [comment]
@tczekajlo Sorry! Not sure from where this is coming from.

**Comment by tczekajlo** [comment]
> @tczekajlo Sorry! Not sure from where this is coming from.

It's something that you can see in the rasa-production and rasa-worker pods. @wochinge Maybe you have seen the error before?

**Comment by wochinge** [comment]
Haven't seen it before. Seems the imports changed so that it's imported now when starting the server 😬 Guess we should set `MPLCONFIGDIR` in the dockerfiles to some temporary directory

**Comment by tczekajlo** [comment]
Cool, thanks for the information. I'll give it a 👀  and add additional configuration to get rid of the error 😄

**Comment by federicotdn** [comment]
@tczekajlo @wochinge just a note (I hadn't realized this before), the two lines in the log that Tomasz shared are completely unrelated. The first one is from OSS `telemetry.py` and the other one from matplotlib.

**Comment by tczekajlo** [comment]
> @tczekajlo @wochinge just a note (I hadn't realized this before), the two lines in the log that Tomasz shared are completely unrelated. The first one is from OSS `common.py` and the other one from matplotlib.

Thanks for pointing it out. Now I see it, Rasa OOS is trying to write to `~/.config/rasa/global.yml`.
