### ISSUE TITLE
templating fails for non semantic versions

### ISSUE THREAD

**Issue by loomsen** [RasaHQ/rasa-x-helm#86]
Hi,
as mentioned [in this comment](https://github.com/RasaHQ/rasa-x-helm/commit/8c7b46f30074371eaeb95c30356ec87611727c3d#commitcomment-43576081), helm teplating fails if rasa.tag is a commit hash.

```
$ helm upgrade $CI_COMMIT_REF_SLUG \
  rasa-x/rasa-x \
  -f deployment/rasa-x/values.yaml \
  -i \
  --namespace $CI_COMMIT_REF_SLUG \
  --create-namespace \
  --set ingress.hosts[0].host=$deployment_url \
  --set ingress.tls[0].hosts[0]=$deployment_url \
  --set ingress.tls[0].secretName=$CI_COMMIT_REF_SLUG-tls 
  --set rasa.tag=$CI_COMMIT_SHA \
  --set app.tag=$CI_COMMIT_SHA \
  --wait \
  --timeout 1200s

Error: template: rasa-x/templates/rasa-x-deployment.yaml:23:33: executing "rasa-x/templates/rasa-x-deployment.yaml" at <include (print $.Template.BasePath "/rasa-config-files-configmap.yaml") .>: error calling include: template: rasa-x/templates/rasa-config-files-configmap.yaml:40:12: executing "rasa-x/templates/rasa-config-files-configmap.yaml" at <semverCompare ">= 1.9.0" .Values.rasa.tag>: error calling semverCompare: Invalid Semantic Version
```

I think this is a very common pattern...

**Comment by loomsen** [comment]
I just noticed this: 

`{{ if semverCompare ">= 1.9.0" .Values.rasa.tag -}}`

It makes having our custom versioning impossible... We should change this too, otherwise we would have to follow your versioning (or at least start with versions > 1.9.0). Also, we are usually having SemVer Tags with a v prepended.

**Comment by loomsen** [comment]
Actually, 

```
      {{ if or (regexMatch ".*(a|rc)[0-9]+" .Values.rasa.tag) (regexMatch "2.*[0-9]+-full" .Values.rasa.tag) (regexMatch "([a-z][0-9])+" .Values.rasa.tag) -}}
      queues:
      - ${RABBITMQ_QUEUE}
      {{- else -}}
      {{ if semverCompare ">= 1.9.0" .Values.rasa.tag -}}
      queues:
      - ${RABBITMQ_QUEUE}
      {{- else -}}
      queue: ${RABBITMQ_QUEUE}
      {{- end }}
      {{- end }}
```

This seems kind of redundant/unnecessary? Or what's the reasoning behind having the separation and the `if` there at all?

**Comment by tczekajlo** [comment]
cc @mprazz 

> I just noticed this:
> 
> `{{ if semverCompare ">= 1.9.0" .Values.rasa.tag -}}`
> 
> It makes having our custom versioning impossible... We should change this too, otherwise we would have to follow your versioning (or at least start with versions > 1.9.0). Also, we are usually having SemVer Tags with a v prepended, like `v1.0.0` or `v1.0.0-hash`

The `semverCompare` function based on the [Semantic Versioning 2.0.0](https://semver.org/), the versions that contain `v` are not semantic versions but it still works, https://semver.org/#is-v123-a-semantic-version, so the `v1.0.0` or `v1.0.0-hash` are ok.

Since the [Rasa 2.0.0, the support for `queue` argument is removed](https://rasa.com/docs/rasa/changelog/#200---2020-10-07). We have to check what version of Rasa is used, but unfortunately, not all versions/tags that are used are valid semantic versions, that's why we have to have the exception.  
```
{{ if or (regexMatch ".*(a|rc)[0-9]+" .Values.rasa.tag) (regexMatch "2.*[0-9]+-full" .Values.rasa.tag) -}}
```
cc @mprazz

**Comment by loomsen** [comment]
Right, it also breaks for commit hashes as mentioned. But then this introduces a whole new necessary naming scheme. Like we would always have to have the version of the rasa base image in our tags. So we would end up with 

`1.9.0-commithash` in development and `1.9.0-v1.0.0`, assuming our internal tag for the rasa image would be `1.0.0`. 
Not very nice imo... Can we think of a better solution here?

**Comment by mprazz** [comment]
Related to [this issue](https://github.com/RasaHQ/rasa-x/issues/3777), though we should evaluate what the best option is

**Comment by wochinge** [comment]
@loomsen @tczekajlo What do you think of separating `rasa.tag` into `rasa.tag` and `rasa.version`?

How it would work:
- `rasa.version` is mandatory and would be used for our `semverCompare` comparisons.
- If empty, `rasa.tag` would be `{{ .Version.rasa.version}}-full` . If `rasa.tag` is provided, we use the provided `rasa.tag` value. 

This would allow:
* to have a backward compatible Helm chart
* arbitrary tag formats
* user's who use the default image don't have to specify two values

**Comment by loomsen** [comment]
Hi @wochinge,

I think this could work, yeah. Our images have either a commit hash or a version tag. So I think those boxes are checked. If I understand you correctly, `rasa.version` would just be something like a helper variable, not actually used as an image tag (except for the case where `rasa.tag` is empty).
So what usually would be `latest` would result in `{{ .Version.rasa.version}}-full`?
Is this correct? 


Just as a sidenote, it seems to be accepted amongst even very big projects (like cert-manager and ingress-nginx) to not necessarily have backward compatible helm charts. Imho sometimes it's easier to split things instead of introducing hard to maintain logic. This is not yet such an example, but I think we should take care not to move into that direction.

I will close my #87 PR then.

**Comment by wochinge** [comment]
> rasa.version would just be something like a helper variable

Exactly. It would be mandatory though so that we can do version comparisons in order to make the helm chart backwards compatible with as many Rasa Open Source versions as possible. 

> So what usually would be latest would result in {{ .Version.rasa.version}}-full?

We actually never use the `latest` tag. We always specify a specific version. Or did I misunderstand you?

> Imho sometimes it's easier to split things instead of introducing hard to maintain logic.

I fully agree 👍 I think at the moment it's very tiny things we do to ensure backwards compatibility. If it would be a lot of pain for a certain change, then I'd also opt to make a release not backwards compatible.

> I will close my #87 PR then.

👍 I'll do a PR this week to solve this

**Comment by tczekajlo** [comment]
> @loomsen @tczekajlo What do you think of separating `rasa.tag` into `rasa.tag` and `rasa.version`?
> 
> How it would work:
> 
> * `rasa.version` is mandatory and would be used for our `semverCompare` comparisons.
> * If empty, `rasa.tag` would be `{{ .Version.rasa.version}}-full` . If `rasa.tag` is provided, we use the provided `rasa.tag` value.
> 
Good idea! 👍
