### ISSUE TITLE
Add support for setting custom labels on pods

### ISSUE THREAD

**Issue by orrshilon** [RasaHQ/rasa-x-helm#94]
The `rasa-x.labels` helper is set on all pods in the chart.
An option to append custom labels to this helper would be nice.

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tczekajlo** [comment]
@orrshilon Thanks for opening the issue. It sounds like a good idea. The rasa-x helm chart is open-source and if you feel like contributing to the project feel free to do so 🚀

**Comment by tczekajlo** [comment]
Resolved by https://github.com/RasaHQ/rasa-x-helm/pull/108
